"use client";
import Link from 'next/link';
import Button from './Button';
import { Menu } from 'lucide-react';

// Sheet components will be generated by shadcn-ui and live at components/ui/sheet
import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';

export default function Header() {
  return (
    <header className="sticky top-0 z-40 backdrop-blur-md bg-white/80 border-b border-slate-200/60 shadow-sm">
      <div className="max-w-6xl mx-auto px-4 py-3 md:py-4 flex items-center justify-between">
        <div className="text-xl font-heading font-semibold text-slate-900">Lhotse</div>

        <nav className="hidden md:flex gap-6 items-center text-slate-900">
          <a href="#services" className="hover:opacity-90">Services</a>
          <a href="#calculator" className="hover:opacity-90">Calculator</a>
          <a href="#enquiry-wizard" className="hover:opacity-90">Book a Discovery Call</a>
          <Button asLink href="#enquiry-wizard">Book a Discovery Call</Button>
        </nav>

        <div className="md:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <button aria-label="Open menu" className="p-2">
                <Menu />
              </button>
            </SheetTrigger>
            <SheetContent position="right" size="w-72">
              <SheetHeader>
                <SheetTitle>Menu</SheetTitle>
              </SheetHeader>

              <nav className="flex flex-col gap-4 mt-4">
                <a href="#services">Services</a>
                <a href="#calculator">Calculator</a>
                <a href="#enquiry-wizard">Book a Discovery Call</a>
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </header>
  );
}
